### ISSUE TITLE
Implement user settings page 

### ISSUE THREAD

**Issue by WebKingdom** [WebKingdom/Life_Tok_App#1]
Create the UI for the user profile settings page and some functionality for updating the user information.

**Comment by alexnaughtonjr** [comment]
`W/sszabo.life_to: Accessing hidden field Landroid/database/sqlite/SQLiteDatabase;->mLock:Ljava/lang/Object; (greylist-max-o, linking, denied)
W/sszabo.life_to: Accessing hidden method Landroid/database/sqlite/SQLiteDatabase;->throwIfNotOpenLocked()V (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/database/sqlite/SQLiteDatabase;->mLock:Ljava/lang/Object; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/database/sqlite/SQLiteDatabase;->throwIfNotOpenLocked()V (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/database/sqlite/SQLiteDatabase;->mLock:Ljava/lang/Object; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/database/sqlite/SQLiteDatabase;->throwIfNotOpenLocked()V (greylist-max-o, linking, denied)
W/sszabo.life_to: Accessing hidden method Landroid/database/sqlite/SQLiteSession;->setTransactionSuccessful()V (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/database/sqlite/SQLiteDatabase;->getThreadDefaultConnectionFlags(Z)I (greylist-max-o, linking, denied)
W/sszabo.life_to: Accessing hidden method Landroid/database/sqlite/SQLiteDatabase;->yieldIfContendedHelper(ZJ)Z (greylist-max-o, linking, denied)
I/chatty: uid=10154(com.sszabo.life_tok) ection primary] identical 1 line
W/sszabo.life_to: Accessing hidden method Landroid/database/sqlite/SQLiteDatabase;->yieldIfContendedHelper(ZJ)Z (greylist-max-o, linking, denied)
W/System: Ignoring header X-Firebase-Locale because its value was null.
W/System: Ignoring header X-Firebase-Locale because its value was null.
W/System: Ignoring header X-Firebase-Locale because its value was null.`

**Comment by alexnaughtonjr** [comment]
^ The above error message occurs when pressing "create account"

**Comment by WebKingdom** [comment]
Working on it. Your issue was caused by accessing the database from a new MAC address that the database did not allow.

**Comment by alexnaughtonjr** [comment]
Hey I made an org repo and invited you https://github.com/Locus-Technologies

**Comment by alexnaughtonjr** [comment]
Also, how are things coming along?

**Comment by WebKingdom** [comment]
Finished issue. Already in master.
